# Generated by Django 5.0.2 on 2024-04-25 06:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalonSamochodowyApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carName', models.CharField(default='Brak', max_length=255)),
                ('carDescription', models.TextField(default='Brak')),
                ('carPrice', models.PositiveSmallIntegerField(default=1)),
                ('carYear', models.DateField(default=datetime.date.today)),
                ('carborrow_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='ListCars',
        ),
    ]
